MAX_COLOR_DENSITY = 255

BLUE = (MAX_COLOR_DENSITY, 0, 0)
GREEN = (0, MAX_COLOR_DENSITY, 0)
RED = (0, 0, MAX_COLOR_DENSITY)

LIGHT_ORANGE = (0, 191, MAX_COLOR_DENSITY)
DEEP_SKY_BLUE = (MAX_COLOR_DENSITY, 191, 0)
